# tests/zsbc.test/01gmp-45.exp

set timeout 3
spawn "$ZSBC" --SCM
send_user "***   GMP - last variable\n"

set test "Check last is updated"
send "151\n2+2\nlast\n515\n"
expect {
	-re "151\[^0-9\]+4\[^0-9\]+4\[^0-9\]+515" { pass "$test" }
	default { fail "$test" }
}

set test "Check last can be updated"
send "161\nlast=3*3\nlast\n616\n"
expect {
	-re "161\[^0-9\]+9\[^0-9\]+616" { pass "$test" }
	default { fail "$test" }
}

set test "Check . alias for last - check it is updated"
send "171\n2+2\nlast\n717\n"
expect {
	-re "171\[^0-9\]+4\[^0-9\]+4\[^0-9\]+717" { pass "$test" }
	default { fail "$test" }
}

set test "Check . alias for last - check it can be updated"
send "181\n.=3*3\n.\n818\n"
expect {
	-re "181\[^0-9\]+9\[^0-9\]+818" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

