# tests/zsbc.test/01gmp-31.exp

set timeout 3
spawn "$ZSBC" --SCM --COPYONUPDATE "$TESTDIR/01gmp-31.b"
send_user "***   GMP - arrays - copyonupdate\n"

set test "Check copyonupdate feature (1)"
expect {
	-re "donothing start\[^0-9\]+copyonupdate: soft array destruction of .*\[^0-9\]+donothing end" { pass "$test" }
	default { fail "$test" }
}

set test "Check copyonupdate feature (2)"
expect {
	-re "doread start\[^0-9\]+5\[^0-9\]+copyonupdate: soft array destruction of .*\[^0-9\]+doread end" { pass "$test" }
	default { fail "$test" }
}

set test "Check copyonupdate feature (3)"
expect {
	-re "dowrite start\[^0-9\]+copyonupdate: copying array .*\[^0-9\]+10\[^0-9\]+dowrite end" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

