# tests/zsbc.test/01gmp-04.exp

set timeout 3
send_user "***   GMP - comparison and logical operators\n"

spawn "$ZSBC" --SCM

set test "Get GMP Library version"
expect {
	-nocase "gmp library" { pass "$test" }
	default { fail "Could not get GMP library version" }
}

set test "Testing <"
send -- "121\n-3<-2\n-2<-2\n-2<-3\n3<2\n2<2\n2<3\n-3<2\n3<-2\n222\n"
expect {
	-re "121\[^0-9\]+1\[^0-9\]+0\[^0-9\]+0\[^0-9\]+0\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+0\[^0-9\]+222\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing <="
send -- "131\n-3<=-2\n-2<=-2\n-2<=-3\n3<=2\n2<=2\n2<=3\n-3<=2\n3<=-2\n232\n"
expect {
	-re "131\[^0-9\]+1\[^0-9\]+1\[^0-9\]+0\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+1\[^0-9\]+0\[^0-9\]+232\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing >"
send -- "141\n-3>-2\n-2>-2\n-2>-3\n3>2\n2>2\n2>3\n-3>2\n3>-2\n242\n"
expect {
	-re "141\[^0-9\]+0\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+0\[^0-9\]+0\[^0-9\]+0\[^0-9\]+1\[^0-9\]+242\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing >="
send -- "171\n-3>=-2\n-2>=-2\n-2>=-3\n3>=2\n2>=2\n2>=3\n-3>=2\n3>=-2\n272\n"
expect {
	-re "171\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+1\[^0-9\]+1\[^0-9\]+0\[^0-9\]+0\[^0-9\]+1\[^0-9\]+272\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing =="
send -- "181\n-3==-2\n-2==-2\n-2==-3\n3==2\n2==2\n2==3\n-3==2\n3==-2\n282\n"
expect {
	-re "181\[^0-9\]+0\[^0-9\]+1\[^0-9\]+0\[^0-9\]+0\[^0-9\]+1\[^0-9\]+0\[^0-9\]+0\[^0-9\]+0\[^0-9\]+282\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing !="
send -- "123\n-3!=-2\n-2!=-2\n-2!=-3\n3!=2\n2!=2\n2!=3\n-3!=2\n3!=-2\n321\n"
expect {
	-re "123\[^0-9\]+1\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+1\[^0-9\]+321\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing &&"
send -- "1918\nprint 0&&0, \":\", 0&&1, \":\", 1&&0, \":\", 1&&1, \"-\"\n0\n1919\n"
expect {
	-re "1918\[^0-9\]+0:0:0:1-0\[^0-9\]+1919\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing ||"
send -- "161\n0||0\n0||1\n1||0\n1||1\n262\n"
expect {
	-re "161\[^0-9\]+0\[^0-9\]+1\[^0-9\]+1\[^0-9\]+1\[^0-9\]+262\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Testing !"
send -- "151\n!0\n!1\n252\n"
expect {
	-re "151\[^0-9\]+1\[^0-9\]+0\[^0-9\]+252\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

