# tests/zsbc.test/01gmp-59.exp

set timeout 3

spawn "/bin/sh" -c "ZSBC_LINE_LENGTH=70 $ZSBC --SCM --numlib bc -l"
send_user "***   GMP - BC_LINE_LENGTH=70 environment variable\n"

set test "Line cut at 69"
send "1\n97^51\n2\n"
expect {
	-re "1\[^0-9\]+21152341408698536954656369019679714480781761307319822114068580183192\[^0-9\]+1593263113495529424965134228709153\[^0-9\]+2" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

