# tests/zsbc.test/01gmp-21.exp

set timeout 3
spawn "$ZSBC" --SCM
send_user "***   GMP - programs - while loop\n"

set test "while (1)"
send "r=1;while(a<128){a=a+1;r=r*2};r\n"
expect {
	"340282366920938463463374607431768211456" { pass "$test" }
	default { fail "$test" }
}

set test "while (1bis)"
send "r=1;\nwhile   (t<128)  \n\n\n   \n   {t=t+1  ;  r=r*2}\n\n;\n\nr\n"
expect {
	"340282366920938463463374607431768211456" { pass "$test" }
	default { fail "$test" }
}

set test "while (2)"
send "while (b<=500) b=b+1; b\n"
expect {
	"501" { pass "$test" }
	default { fail "$test" }
}

set test "while (2bis)"
send "\n   \n\n      while     (b<=500)\n\n\n\n\nb=b+1;b\n"
expect {
	"501" { pass "$test" }
	default { fail "$test" }
}

set test "while (3)"
send "while(c<5)(c=c+1);\"end\";c\n"
expect {
	-re "1\[^0-9\]+2\[^0-9\]+3\[^0-9\]+4\[^0-9\]+5\[^0-9\]+end5\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "while (3bis)"
send "     c  =   0 ;     while ( c  < 5 )          (c=c+1)\n\"end\";c\n"
expect {
	-re "1\[^0-9\]+2\[^0-9\]+3\[^0-9\]+4\[^0-9\]+5\[^0-9\]+end5\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

