# tests/zsbc.test/01gmp-49.exp

set timeout 3
spawn "$ZSBC" --SCM "$TESTDIR/01gmp-49.b"
send_user "***   GMP - function arguments\n"

set test "Check error message is accurate"
send "120\nf()\n121\n"
expect {
	-re "120\[^0-9\]+Error:.*Function a not defined\[^0-9\]+121" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

