# tests/zsbc.test/01gmp-48.exp

set timeout 3
spawn "$ZSBC" --SCM "$TESTDIR/01gmp-48.b"
send_user "***   GMP - function arguments\n"

set test "Round 1"
expect {
	"ROUND1-1:500;501" { pass "$test" }
	default { fail "$test" }
}

set test "Round 1 bis"
expect {
	"ROUND1-2:1500;1503" { pass "$test" }
	default { fail "$test" }
}

set test "Round 2"
expect {
	"ROUND2-1:500;501" { pass "$test" }
	default { fail "$test" }
}

set test "Round 2 bis"
expect {
	"ROUND2-2:1500;1503" { pass "$test" }
	default { fail "$test" }
}

set test "Round 3"
expect {
	"ROUND3-1:1234;501503" { pass "$test" }
	default { fail "$test" }
}

set test "Round 3 bis"
expect {
	"ROUND3-2:1500;1503" { pass "$test" }
	default { fail "$test" }
}

set test "Round 4"
expect {
	"ROUND4-1:3703;1504511" { pass "$test" }
	default { fail "$test" }
}

set test "Round 3 bis"
expect {
	"ROUND4-2:1500;1503" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

