# tests/zsbc.test/02bc-70.exp

set timeout 3
spawn "$ZSBC" --SCM --numlib bc
send_user "***   BC - Numbers input\n"

set test "Misc numbers"
send "9\nA\nF\nG\n99\nAA\nFF\n0G\n1111\n"
expect {
	-re "9\[^0-9\]+10\[^0-9\]+15\[^0-9\]+.*Illegal number\[^0-9\]+99\[^0-9\]+99\[^0-9\]+99\[^0-9\]+.*Illegal number\[^0-9\]+1111\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Input one number (1)"
send "aa=read()\n150AG1\n5771\naa^2\n5772\n"
expect {
	-re "5771\[^0-9\]+2277081\[^0-9\]+5772" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

