# tests/zsbc.test/zsbc21.exp

set timeout 3
spawn "$ZSBC" -V
send_user "***   Arrays\n"

set test "Array"
send -- "i=0;while(i<=1000){va\[i\]=i+1;i+=1}\ni=998;while(i<=1001){va\[i\];i+=1}\n"
expect {
	-re "999\[^0-9\]+1000\[^0-9\]+1001\[^0-9\]+0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Increment (1)"
send -- "101\na++\n202\na\n"
expect {
	-re "101\[^0-9\]+0\[^0-9\]+202\[^0-9\]+1\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Increment (2)"
send -- "303\n++a\n404\n"
expect {
	-re "303\[^0-9\]+2\[^0-9\]+404\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Increment (3)"
send -- "a\[0\]=55;101\na\[0\]++\n202\na\[0\]\n"
expect {
	-re "101\[^0-9\]+55\[^0-9\]+202\[^0-9\]+56\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Increment (4)"
send -- "a\[0\]=77;303\n++a\[0\]\n404\na\[0\]\n"
expect {
	-re "303\[^0-9\]+78\[^0-9\]+404\[^0-9\]+78\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Checking object count ref is null"
send "quit\n"
expect {
	-re "OK.*number count.*should be 0.*: 0\[^0-9\]+OK.*expr_t.*count.*should be 0.*: 0\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

