# tests/zsbc.test/zsbc2.exp

set timeout 3
spawn "$ZSBC" -q
send_user "***   Error cases tests\n"

set test "Syntax error '101+'"
send "101+\n"
expect {
	-re "syntax error.*" { pass "$test" }
	default { fail "$test" }
}

set test "Syntax error '101++102'"
send "101++202\n"
expect {
	-re "syntax error.*" { pass "$test" }
	default { fail "$test" }
}

set test "Syntax error '^101'"
send "^101\n"
expect {
	-re "syntax error.*" { pass "$test" }
	default { fail "$test" }
}

set test "Illegal character"
send "@\n"
expect {
	-re "illegal character.*" { pass "$test" }
	default { fail "$test" }
}

send "quit\n"

