# tests/zsbc.test/zsbc10.exp

set timeout 3
spawn "$ZSBC" -q
send_user "***   libswitch\n"

set test "libswitch"
send "a=101\nlibswitch \"bc\"\na=202\nlibswitch \"gmp\"\n303\na\nlibswitch \"bc\"\na\n404\n"
expect {
	-re "303\[^0-9\]+101\[^0-9\]+202\[^0-9\]+404\[^0-9\]+" { pass "$test" }
	default { fail "$test" }
}

set test "Check quit does not crash"
send "quit\n"
expect {
	":" { fail "$test" }
	default { pass "$test" }
}

